meta_product_name: "To-Do Quest"
meta_title: "To-Do Quest - Where every task becomes a quest"
meta_description: "To-Do Quest is a gamified to-do list app that turns your tasks into quests. Complete quests to earn rewards and level up your character."
meta_image: "/app/assets/images/TDQ-cover.png"
